name: Compile Poseidon on Ubuntu 20.04 with gnu compilers

on: [ push, pull_request ]

jobs:
  compile-with-amrex_gnu:
    name: Compile Poseidon on Ubuntu 20.04 with gnu compilers
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      POSEIDON_MACHINE_NAME: github_ubuntu-20.04_gnu
    steps:
      - name: Checkout Poseidon
        uses: actions/checkout@v3

      - name: Checkout amrex
        uses: actions/checkout@v3
        with:
          repository: dunhamsj/amrex
          path: amrex
          ref: MeshRefinement_DG

      - name: Update Ubuntu
        run: |
          sudo apt-get -y install libhdf5-dev
          sudo apt-get -y install mpich
          sudo apt-get -y update
      - name: Set Environment Variables
        run: |
          echo "POSEIDON_ACTIVE_DIR=${GITHUB_WORKSPACE}"                >> ${GITHUB_ENV}
          echo "AMREX_DIR=${GITHUB_WORKSPACE}/amrex"                    >> ${GITHUB_ENV}
          echo "HDF5_ROOT=/usr/lib/x86_64-linux-gnu/hdf5/serial"        >> ${GITHUB_ENV}
          echo "LAPACK_ROOT=/usr/lib/x86_64-linux-gnu/lapack"           >> ${GITHUB_ENV}
          echo "BLAS_ROOT=/usr/lib/x86_64-linux-gnu/blas"               >> ${GITHUB_ENV}
          echo "HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial"         >> ${GITHUB_ENV}
          echo "HDF5_INC=/usr/lib/x86_64-linux-gnu/hdf5/serial/include" >> ${GITHUB_ENV}
          echo "HDF5_LIB=/usr/lib/x86_64-linux-gnu/hdf5/serial/lib"     >> ${GITHUB_ENV}
          echo "LAPACK_DIR=/usr/lib/x86_64-linux-gnu/lapack"            >> ${GITHUB_ENV}
          echo "LAPACK_LIB=/usr/lib/x86_64-linux-gnu/lapack"            >> ${GITHUB_ENV}
      - name: Compile Drivers/Yahil Profile - XCFC - Native
        timeout-minutes: 2
        run: |
          cd ${POSEIDON_ACTIVE_DIR}/Drivers/Yahil\ Profile\ -\ XCFC\ -\ Native/
          make main
          make run
          make clean
      - name: Compile Drivers/Yahil Profile - XCFC - AMReX
        timeout-minutes: 8
        if: ${{ !cancelled() }}
        run: |
          cd ${POSEIDON_ACTIVE_DIR}/Drivers/Yahil\ Profile\ -\ XCFC\ -\ AMReX/
          make
          ls
          mpiexec -n 1 ./Yahil_XCFC_AMReX1d.gnu.DEBUG.MPI.ex inputs_Poseidon_CI
          make clean
