name: Compile thornado on Ubuntu 20.04 with gnu compilers

on: [ push, pull_request ]

jobs:
  thornado-compile-with-amrex_gnu:
    name: Compile thornado on Ubuntu 20.04 with gnu compilers
    runs-on: ubuntu-20.04
    env:
      THORNADO_MACHINE: gh-runner_ubuntu-20.04_gnu
    steps:
      - name: Checkout Poseidon
        uses: actions/checkout@v3

      - name: Checkout amrex
        uses: actions/checkout@v3
        with:
          repository: dunhamsj/amrex
          path: amrex
          ref: MeshRefinement_DG
          
      - name: Checkout thornado
        uses: actions/checkout@v3
        with:
          repository: endeve/thornado
          path: thornado
          ref:  InterfaceWithPoseidon
          
      - name: Checkout weaklib
        uses: actions/checkout@v3
        with:
          repository: starkiller-astro/weaklib
          path: weaklib
    
      - name: Update Ubuntu
        run: |
          sudo apt-get -y install libhdf5-dev
          sudo apt-get -y install mpich
          sudo apt-get -y update
    
      - name: Set Environment Variables
        run: |
          echo "THORNADO_DIR=${GITHUB_WORKSPACE}/thornado"      >> ${GITHUB_ENV}
          echo "HDF5_INC=/usr/include/hdf5/serial"              >> ${GITHUB_ENV}
          echo "HDF5_LIB=/usr/lib/x86_64-linux-gnu/hdf5/serial" >> ${GITHUB_ENV}
          echo "LAPACK_LIB=/usr/lib/x86_64-linux-gnu"           >> ${GITHUB_ENV}
          echo "BLAS_LIB=/usr/lib/x86_64-linux-gnu"             >> ${GITHUB_ENV}
          echo "WEAKLIB_DIR=${GITHUB_WORKSPACE}/weaklib"        >> ${GITHUB_ENV}
          echo "AMREX_DIR=${GITHUB_WORKSPACE}/amrex"            >> ${GITHUB_ENV}
          echo "POSEIDON_DIR=${GITHUB_WORKSPACE}"      >> ${GITHUB_ENV}

      - name: Compile SandBox/YahilCollapse_XCFC
        run: |
          cd ${THORNADO_DIR}/SandBox/YahilCollapse_XCFC/Executables
          make
          make clobber


      - name: Compile SandBox/AdiabaticCollapse_XCFC
        run: |
          cd ${THORNADO_DIR}/SandBox/AdiabaticCollapse_XCFC/Executables
          make
          make clobber

      - name: Compile SandBox/AMReX/Applications/YahilCollapse_XCFC
        run: |
          ls
          ls ${POSEIDON_DIR}
          ls ${POSEIDON_DIR}/Build
          cd ${THORNADO_DIR}/SandBox/AMReX/Applications/YahilCollapse_XCFC
          make -j -l6
          make realclean


      - name: Compile SandBox/AMReX/Applications/AdiabaticCollapse_XCFC
        run: |
          cd ${THORNADO_DIR}/SandBox/AMReX/Applications/AdiabaticCollapse_XCFC
          make -j -l6
          make realclean


      - name: Compile SandBox/AMReX/Applications/CoreCollapseSupernova_XCFC
        run: |
          cd ${THORNADO_DIR}/SandBox/AMReX/Applications/CoreCollapseSupernova_XCFC
          make -j -l6
          make realclean
